In [1]:
import pandas as pd
import numpy as np
import datetime

In [6]:
df = pd.read_csv("old_statlines.csv")

In [7]:
df

,id,espn_name,sr_name,kp_name,KenPomRank,KenPomVal,BPIrank,BPIval,SRS,o_eff,...,ppg,papg,Pace,Three_Par,True_Shoot,Tov,Opp_Three_Par,Opp_True_Shoot,Opp_Tov,record_date
0,1161,Abilene Christian,Abilene Christian,Abilene Christian,152,1.35,150,1.0,-1.91,101.19,...,73.6,63.6,67.2,0.345,0.565,15.5,0.333,0.529,21.5,2019-09-01 20:27:43
1,1162,Air Force,Air Force,Air Force,243,-7.06,287,-6.5,-4.28,100.24,...,68.1,71.7,67.4,0.400,0.541,17.4,0.462,0.555,15.7,2019-09-01 20:27:43
2,1163,Akron,Akron,Akron,108,5.87,123,3.0,4.86,99.36,...,68.8,63.8,68.5,0.477,0.515,15.0,0.382,0.481,16.6,2019-09-01 20:27:43
3,1164,Alabama,Alabama,Alabama,64,10.68,67,6.9,9.45,108.68,...,72.0,71.6,69.8,0.369,0.533,16.8,0.327,0.521,14.7,2019-09-01 20:27:43
4,1165,Alabama A&M,Alabama A&M,Alabama A&M,344,-22.17,345,-14.5,-19.23,84.53,...,60.6,71.4,67.5,0.320,0.479,19.4,0.384,0.558,18.3,2019-09-01 20:27:43
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44393,47738,Wright State,Wright State,Wright St.,133,3.47,126,2.5,2.46,102.68,...,80.6,70.8,73.1,0.340,0.546,14.4,0.328,0.497,16.6,2020-04-05 15:30:14
44394,47739,Wyoming,Wyoming,Wyoming,246,-6.79,288,-6.4,-3.05,93.62,...,62.7,69.9,67.6,0.465,0.520,17.3,0.416,0.535,16.4,2020-04-05 15:30:14
44395,47740,Xavier,Xavier,Xavier,45,13.90,50,8.6,12.57,106.80,...,70.7,67.6,69.1,0.347,0.516,16.9,0.363,0.500,16.3,2020-04-05 15:30:14
44396,47741,Yale,Yale,Yale,58,11.57,55,8.4,6.63,105.97,...,76.3,65.1,68.2,0.414,0.573,16.3,0.405,0.492,15.5,2020-04-05 15:30:14
44397,47742,Youngstown St,Youngstown State,Youngstown St.,232,-5.59,232,-3.5,-5.56,99.58,...,72.8,71.2,68.6,0.372,0.511,14.5,0.331,0.526,15.1,2020-04-05 15:30:14

In [15]:
df.columns

Index(['id', 'espn_name', 'sr_name', 'kp_name', 'KenPomRank', 'KenPomVal',
       'BPIrank', 'BPIval', 'SRS', 'o_eff', 'd_eff', 'ppg', 'papg', 'Pace',
       'Three_Par', 'True_Shoot', 'Tov', 'Opp_Three_Par', 'Opp_True_Shoot',
       'Opp_Tov', 'record_date'],
      dtype='object')

In [45]:
kpval = df[['kp_name','KenPomVal','record_date']]
kpval['Metric'] = 'KenPom'
kpval = kpval.rename(columns={"kp_name": "team_name", "KenPomVal": "Value"})

bpival = df[['espn_name','BPIval','record_date']]
bpival['Metric'] = 'BPI'
bpival = bpival.rename(columns={"espn_name": "team_name", "BPIval": "Value"})

srsval = df[['sr_name','SRS','record_date']]
srsval['Metric'] = 'SRS'
srsval = srsval.rename(columns={"sr_name": "team_name", "SRS": "Value"})

oeffval = df[['sr_name','o_eff','record_date']]
oeffval['Metric'] = 'O_Efficiency'
oeffval = oeffval.rename(columns={"sr_name": "team_name", "o_eff": "Value"})

deffval = df[['sr_name','d_eff','record_date']]
deffval['Metric'] = 'D_Efficiency'
deffval = deffval.rename(columns={"sr_name": "team_name", "d_eff": "Value"})

ppgval = df[['sr_name','ppg','record_date']]
ppgval['Metric'] = 'PPG'
ppgval = ppgval.rename(columns={"sr_name": "team_name", "ppg": "Value"})

papgval = df[['sr_name','papg','record_date']]
papgval['Metric'] = 'PAPG'
papgval = papgval.rename(columns={"sr_name": "team_name", "papg": "Value"})

paceval = df[['sr_name','Pace','record_date']]
paceval['Metric'] = 'Pace'
paceval = paceval.rename(columns={"sr_name": "team_name", "Pace": "Value"})

threeparval = df[['sr_name','Three_Par','record_date']]
threeparval['Metric'] = 'Three_Point_Attempt_Rate'
threeparval = threeparval.rename(columns={"sr_name": "team_name", "Three_Par": "Value"})

trueshootval = df[['sr_name','True_Shoot','record_date']]
trueshootval['Metric'] = 'True_Shooting'
trueshootval = trueshootval.rename(columns={"sr_name": "team_name", "True_Shoot": "Value"})

tovval = df[['sr_name','Tov','record_date']]
tovval['Metric'] = 'Turnover_Perc'
tovval = tovval.rename(columns={"sr_name": "team_name", "Tov": "Value"})

oppthreeparval = df[['sr_name','Opp_Three_Par','record_date']]
oppthreeparval['Metric'] = 'Opp_Three_Point_Attempt_Rate'
oppthreeparval = oppthreeparval.rename(columns={"sr_name": "team_name", "Opp_Three_Par": "Value"})

opptrueshootval = df[['sr_name','Opp_True_Shoot','record_date']]
opptrueshootval['Metric'] = 'Opp_True_Shooting'
opptrueshootval = opptrueshootval.rename(columns={"sr_name": "team_name", "Opp_True_Shoot": "Value"})

opptovval = df[['sr_name','Opp_Tov','record_date']]
opptovval['Metric'] = 'Opp_Turnover_Perc'
opptovval = opptovval.rename(columns={"sr_name": "team_name", "Opp_Tov": "Value"})

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:46: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:50: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:54: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [49]:
result = kpval.append([bpival,srsval,oeffval,deffval,ppgval,papgval,paceval,threeparval,trueshootval,tovval,oppthreeparval,opptrueshootval,opptovval])

In [50]:
result = result[['team_name','Metric','Value','record_date']]

               team_name  Value          record_date             Metric
0      Abilene Christian   1.35  2019-09-01 20:27:43             KenPom
1              Air Force  -7.06  2019-09-01 20:27:43             KenPom
2                  Akron   5.87  2019-09-01 20:27:43             KenPom
3                Alabama  10.68  2019-09-01 20:27:43             KenPom
4            Alabama A&M -22.17  2019-09-01 20:27:43             KenPom
...                  ...    ...                  ...                ...
44393       Wright State  16.60  2020-04-05 15:30:14  Opp_Turnover_Perc
44394            Wyoming  16.40  2020-04-05 15:30:14  Opp_Turnover_Perc
44395             Xavier  16.30  2020-04-05 15:30:14  Opp_Turnover_Perc
44396               Yale  15.50  2020-04-05 15:30:14  Opp_Turnover_Perc
44397   Youngstown State  15.10  2020-04-05 15:30:14  Opp_Turnover_Perc

[621572 rows x 4 columns]

In [43]:
kpval

               team_name  Value          record_date  Metric
0      Abilene Christian   1.35  2019-09-01 20:27:43  KenPom
1              Air Force  -7.06  2019-09-01 20:27:43  KenPom
2                  Akron   5.87  2019-09-01 20:27:43  KenPom
3                Alabama  10.68  2019-09-01 20:27:43  KenPom
4            Alabama A&M -22.17  2019-09-01 20:27:43  KenPom
...                  ...    ...                  ...     ...
44393         Wright St.   3.47  2020-04-05 15:30:14  KenPom
44394            Wyoming  -6.79  2020-04-05 15:30:14  KenPom
44395             Xavier  13.90  2020-04-05 15:30:14  KenPom
44396               Yale  11.57  2020-04-05 15:30:14  KenPom
44397     Youngstown St.  -5.59  2020-04-05 15:30:14  KenPom

[44398 rows x 4 columns]